name: Copy File from MDevopsD/test Repo

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your main repository
      - name: Checkout main repository
        uses: actions/checkout@v3

      # Step 2: Checkout the MDevopsD/test repository (specify branch if needed)
      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: MDevopsD/test
          ref: main  # Specify the branch explicitly
          path: external-repo
          token: ${{ secrets.OTHER_REPO_TOKEN }}  # Use your secret PAT here

      # Step 3: Copy the file from external repo to a local folder
      - name: Copy file to workspace folder
        run: |
          mkdir -p my-folder  # Replace with your desired folder
          cp external-repo/path/to/your-file.txt my-folder/
