name: Tar multiple folders

on:
  workflow_dispatch:

jobs:
  tar-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load .env variables
        run: |
          set -a
          source .env
          set +a
          echo "Folders loaded: $FOLDERS"

      - name: Show folder contents
        run: |
          for folder in $FOLDERS; do
            echo "Checking $folder"
            ls -la "$folder" || echo "Missing: $folder"
          done

      - name: Create output directory
        run: mkdir -p Myfolder

      - name: Create tar.gz
        run: |
          tar -czf Myfolder/TEST.tar.gz $FOLDERS
