name: Run in HOME Directory

on:
  push:
    branches:
      - main

jobs:
  run-in-home:
    runs-on: ubuntu-latest

    env:
      HOME_DIR: $HOME  # Explicitly pass $HOME to GitHub Actions' env context

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run command in $HOME
        run: |
          echo "Running from: $PWD"
          ls -la
        working-directory: ${{ env.HOME_DIR }}
