name: Release on Changes Without Tags

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get current commit
      id: current
      run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Fetch last released commit from state branch
      id: last
      run: |
        git fetch origin release-state:release-state || git checkout -b release-state
        LAST_COMMIT=$(git show origin/release-state:last_commit.txt 2>/dev/null || echo "")
        echo "Last release commit: $LAST_COMMIT"
        echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT

    - name: Check if release is needed
      id: check
      run: |
        if [ "${{ steps.current.outputs.hash }}" != "${{ steps.last.outputs.last_commit }}" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Run release if changed
      if: steps.check.outputs.changed == 'true'
      run: |
        echo "Changes detected — releasing..."
        # Your release logic here (e.g., tag, deploy, upload, etc.)

    - name: Update last_commit.txt and push to state branch
      if: steps.check.outputs.changed == 'true'
      run: |
        echo "${{ steps.current.outputs.hash }}" > last_commit.txt
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git checkout -B release-state
        git add last_commit.txt
        git commit -m "Update last release commit"
        git push origin release-state --force
