name: Release on Repo Changes

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-if-new-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current commit SHA
        id: current
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Download last released SHA artifact
        uses: actions/download-artifact@v4
        with:
          name: last-released-sha
        continue-on-error: true  # In case no artifact exists yet

      - name: Read last released SHA
        id: get-last-sha
        run: |
          if [ -f last_sha.txt ]; then
            LAST_SHA=$(cat last_sha.txt)
          else
            LAST_SHA=""
          fi
          echo "Last released SHA: $LAST_SHA"
          echo "last_sha=$LAST_SHA" >> $GITHUB_OUTPUT
          

      - name: Compare with last released SHA
        id: compare
        run: |
          if [ "${{ steps.current.outputs.sha }}" = "${{ steps.get-last-sha.outputs.last_sha }}" ]; then
            echo "No new commit to release."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "New commit detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Perform release actions
        if: steps.compare.outputs.changed == 'true'
        run: |
          echo "✅ Releasing commit ${{ steps.current.outputs.sha }}..."
          # Your actual release logic

      - name: Upload current SHA as artifact
        if: steps.compare.outputs.changed == 'true'
        run: echo "${{ steps.current.outputs.sha }}" > last_sha.txt

      - name: Save artifact (last released SHA)
        if: steps.compare.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-released-sha
          path: last_sha.txt
