name: Tar from JSON Input (Jenkins-style)

on:
  push:

jobs:
  tar-folders:
    runs-on: ubuntu-latest  # Must have access to /folders

    env:
      FOLDERS_JSON: '[
        "/folders/folder1",
        "/folders/folder2",
        "/folders/folder3"
      ]'

    steps:
      - name: create folder 
        run |
          mkdir -p /folders/folder1 
          mkdir -p /folders/folder2
          mkdir -p /folders/folder3
       
      - name: Parse JSON and run tar
        run: |
          # Convert JSON array to space-separated folder list
          FOLDERS=$(echo "$FOLDERS_JSON" | jq -r '.[]' | xargs)
          
          echo "Tarring folders: $FOLDERS"
          
          # Run tar with all folders in one command (like Jenkins)
          tar -czf selected-folders.tar.gz $FOLDERS

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: selected-folders
          path: selected-folders.tar.gz
