name: Tar from JSON Input (Jenkins-style)

on:
  push:

jobs:
  tar-folders:
    runs-on: ubuntu-latest

    env:
      FOLDERS_JSON: '[ "./folders/folder1", "./folders/folder2", "./folders/folder3" ]'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create folders for testing
        run: |
          mkdir -p ./folders/folder1
          mkdir -p ./folders/folder2
          mkdir -p ./folders/folder3

      - name: Parse JSON and run tar
        run: |
          # Convert JSON array to space-separated folder list
          FOLDERS=$(echo "$FOLDERS_JSON" | jq -r '.[]' | xargs)
          echo "Tarring folders: $FOLDERS"
          tar -czf selected-folders.tar.gz $FOLDERS
          tar -xvf  selected-folders.tar.gz


